<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\City;

class CityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DB::insert["
        // INSERT INTO 'cities' ['id', 'province_id', 'name''name' => , 'type', 'postal_code', 'created_at', 'updated_at') VALUES
        $data = [
        ['id' => 1, 'province_id' => 21, 'name' => 'Aceh Barat', 'type' => 'Kabupaten', 'postal_code' => '23681'],
        ['id' => 2, 'province_id' => 21, 'name' => 'Aceh Barat Daya', 'type' => 'Kabupaten', 'postal_code' => '23764'],
        ['id' => 3, 'province_id' => 21, 'name' => 'Aceh Besar', 'type' => 'Kabupaten', 'postal_code' =>'23951'],
        ['id' => 4, 'province_id' => 21, 'name' => 'Aceh Jaya', 'type' => 'Kabupaten', 'postal_code' =>'23654'],
        ['id' => 5, 'province_id' => 21, 'name' => 'Aceh Selatan', 'type' => 'Kabupaten', 'postal_code' =>'23719'],
        ['id' => 6, 'province_id' => 21, 'name' => 'Aceh Singkil', 'type' => 'Kabupaten', 'postal_code' =>'24785'],
        ['id' => 7, 'province_id' => 21, 'name' => 'Aceh Tamiang', 'type' => 'Kabupaten', 'postal_code' =>'24476'],
        ['id' => 8, 'province_id' => 21, 'name' => 'Aceh Tengah', 'type' => 'Kabupaten', 'postal_code' =>'24511'],
        ['id' => 9, 'province_id' => 21, 'name' => 'Aceh Tenggara', 'type' => 'Kabupaten', 'postal_code' =>'24611'],
        ['id' => 10,  'province_id' => 21, 'name' => 'Aceh Timur', 'type' => 'Kabupaten', 'postal_code' =>'24454'],
        ['id' => 11,  'province_id' => 21, 'name' => 'Aceh Utara', 'type' => 'Kabupaten', 'postal_code' =>'24382'],
        ['id' => 12,  'province_id' => 32, 'name' => 'Agam', 'type' => 'Kabupaten', 'postal_code' =>'26411'],
        ['id' => 13,  'province_id' => 23, 'name' => 'Alor', 'type' => 'Kabupaten', 'postal_code' =>'85811'],
        ['id' => 14,  'province_id' => 19, 'name' => 'Ambon', 'type' => 'Kota', 'postal_code' => '97222'],
        ['id' => 15,  'province_id' => 34, 'name' => 'Asahan', 'type' => 'Kabupaten', 'postal_code' =>'21214'],
        ['id' => 16,  'province_id' => 24, 'name' => 'Asmat', 'type' => 'Kabupaten', 'postal_code' =>'99777'],
        ['id' => 17,  'province_id' => 1,  'name' => 'Badung', 'type' => 'Kabupaten', 'postal_code' =>'80351'],
        ['id' => 18,  'province_id' => 13, 'name' => 'Balangan', 'type' => 'Kabupaten', 'postal_code' =>'71611'],
        ['id' => 19,  'province_id' => 15, 'name' => 'Balikpapan', 'type' => 'Kota', 'postal_code' => '76111'],
        ['id' => 20,  'province_id' => 21, 'name' => 'Banda Aceh', 'type' => 'Kota', 'postal_code' => '23238'],
        ['id' => 21,  'province_id' => 18, 'name' => 'Bandar Lampung', 'type' => 'Kota', 'postal_code' => '35139'],
        ['id' => 22,  'province_id' => 9, 'name' =>  'Bandung', 'type' => 'Kabupaten', 'postal_code' =>'40311'],
        ['id' => 23,  'province_id' => 9, 'name' =>  'Bandung', 'type' => 'Kota', 'postal_code' => '40111'],
        ['id' => 24,  'province_id' => 9, 'name' =>  'Bandung Barat', 'type' => 'Kabupaten', 'postal_code' =>'40721'],
        ['id' => 25,  'province_id' => 29, 'name' => 'Banggai', 'type' => 'Kabupaten', 'postal_code' =>'94711'],
        ['id' => 26,  'province_id' => 29, 'name' => 'Banggai Kepulauan', 'type' => 'Kabupaten', 'postal_code' =>'94881'],
        ['id' => 27,  'province_id' => 2, 'name' => 'Bangka', 'type' => 'Kabupaten', 'postal_code' =>'33212'],
        ['id' => 28,  'province_id' => 2, 'name' => 'Bangka Barat', 'type' => 'Kabupaten', 'postal_code' =>'33315'],
        ['id' => 29,  'province_id' => 2, 'name' => 'Bangka Selatan', 'type' => 'Kabupaten', 'postal_code' =>'33719'],
        ['id' => 30,  'province_id' => 2, 'name' => 'Bangka Tengah', 'type' => 'Kabupaten', 'postal_code' =>'33613'],
        ['id' => 31,  'province_id' => 11, 'name' => 'Bangkalan', 'type' => 'Kabupaten', 'postal_code' =>'69118'],
        ['id' => 32,  'province_id' => 1, 'name' => 'Bangli', 'type' => 'Kabupaten', 'postal_code' =>'80619'],
        ['id' => 33,  'province_id' => 13, 'name' => 'Banjar', 'type' => 'Kabupaten', 'postal_code' =>'70619'],
        ['id' => 34,  'province_id' => 9, 'name' => 'Banjar', 'type' => 'Kota', 'postal_code' => '46311'],
        ['id' => 35,  'province_id' => 13, 'name' => 'Banjarbaru', 'type' => 'Kota', 'postal_code' => '70712'],
        ['id' => 36,  'province_id' => 13, 'name' => 'Banjarmasin', 'type' => 'Kota', 'postal_code' => '70117'],
        ['id' => 37,  'province_id' => 10, 'name' => 'Banjarnegara', 'type' => 'Kabupaten', 'postal_code' =>'53419'],
        ['id' => 38,  'province_id' => 28, 'name' => 'Bantaeng', 'type' => 'Kabupaten', 'postal_code' =>'92411'],
        ['id' => 39,  'province_id' => 5, 'name' =>  'Bantul', 'type' => 'Kabupaten', 'postal_code' =>'55715'],
        ['id' => 40,  'province_id' => 33, 'name' => 'Banyuasin', 'type' => 'Kabupaten', 'postal_code' =>'30911'],
        ['id' => 41,  'province_id' => 10, 'name' => 'Banyumas', 'type' => 'Kabupaten', 'postal_code' =>'53114'],
        ['id' => 42,  'province_id' => 11, 'name' => 'Banyuwangi', 'type' => 'Kabupaten', 'postal_code' =>'68416'],
        ['id' => 43,  'province_id' => 13, 'name' => 'Barito Kuala', 'type' => 'Kabupaten', 'postal_code' =>'70511'],
        ['id' => 44,  'province_id' => 14, 'name' => 'Barito Selatan', 'type' => 'Kabupaten', 'postal_code' =>'73711'],
        ['id' => 45,  'province_id' => 14, 'name' => 'Barito Timur', 'type' => 'Kabupaten', 'postal_code' =>'73671'],
        ['id' => 46,  'province_id' => 14, 'name' => 'Barito Utara', 'type' => 'Kabupaten', 'postal_code' =>'73881'],
        ['id' => 47,  'province_id' => 28, 'name' => 'Barru', 'type' => 'Kabupaten', 'postal_code' =>'90719'],
        ['id' => 48,  'province_id' => 17, 'name' => 'Batam', 'type' => 'Kota', 'postal_code' => '29413'],
        ['id' => 49,  'province_id' => 10, 'name' => 'Batang', 'type' => 'Kabupaten', 'postal_code' =>'51211'],
        ['id' => 50,  'province_id' => 8, 'name' => 'Batang Hari', 'type' => 'Kabupaten', 'postal_code' =>'36613'],
        ['id' => 51,  'province_id' => 11, 'name' => 'Batu', 'type' => 'Kota', 'postal_code' => '65311'],
        ['id' => 52,  'province_id' => 34, 'name' => 'Batu Bara', 'type' => 'Kabupaten', 'postal_code' =>'21655'],
        ['id' => 53,  'province_id' => 30, 'name' => 'Bau-Bau', 'type' => 'Kota', 'postal_code' => '93719'],
        ['id' => 54,  'province_id' => 9, 'name' => 'Bekasi', 'type' => 'Kabupaten', 'postal_code' =>'17837'],
        ['id' => 55,  'province_id' => 9, 'name' => 'Bekasi', 'type' => 'Kota', 'postal_code' => '17121'],
        ['id' => 56,  'province_id' => 2, 'name' => 'Belitung', 'type' => 'Kabupaten', 'postal_code' =>'33419'],
        ['id' => 57,  'province_id' => 2, 'name' => 'Belitung Timur', 'type' => 'Kabupaten', 'postal_code' =>'33519'],
        ['id' => 58,  'province_id' => 23, 'name' => 'Belu', 'type' => 'Kabupaten', 'postal_code' =>'85711'],
        ['id' => 59,  'province_id' => 21, 'name' => 'Bener Meriah', 'type' => 'Kabupaten', 'postal_code' =>'24581'],
        ['id' => 60,  'province_id' => 26, 'name' => 'Bengkalis', 'type' => 'Kabupaten', 'postal_code' =>'28719'],
        ['id' => 61,  'province_id' => 12, 'name' => 'Bengkayang', 'type' => 'Kabupaten', 'postal_code' =>'79213'],
        ['id' => 62,  'province_id' => 4, 'name' => 'Bengkulu', 'type' => 'Kota', 'postal_code' => '38229'],
        ['id' => 63,  'province_id' => 4, 'name' => 'Bengkulu Selatan', 'type' => 'Kabupaten', 'postal_code' =>'38519'],
        ['id' => 64,  'province_id' => 4, 'name' => 'Bengkulu Tengah', 'type' => 'Kabupaten', 'postal_code' =>'38319'],
        ['id' => 65,  'province_id' => 4, 'name' => 'Bengkulu Utara', 'type' => 'Kabupaten', 'postal_code' =>'38619'],
        ['id' => 66,  'province_id' => 15, 'name' => 'Berau', 'type' => 'Kabupaten', 'postal_code' =>'77311'],
        ['id' => 67,  'province_id' => 24, 'name' => 'Biak Numfor', 'type' => 'Kabupaten', 'postal_code' =>'98119'],
        ['id' => 68,  'province_id' => 22, 'name' => 'Bima', 'type' => 'Kabupaten', 'postal_code' =>'84171'],
        ['id' => 69,  'province_id' => 22, 'name' => 'Bima', 'type' => 'Kota', 'postal_code' => '84139'],
        ['id' => 70,  'province_id' => 34, 'name' => 'Binjai', 'type' => 'Kota', 'postal_code' => '20712'],
        ['id' => 71,  'province_id' => 17, 'name' => 'Bintan', 'type' => 'Kabupaten', 'postal_code' =>'29135'],
        ['id' => 72,  'province_id' => 21, 'name' => 'Bireuen', 'type' => 'Kabupaten', 'postal_code' =>'24219'],
        ['id' => 73,  'province_id' => 31, 'name' => 'Bitung', 'type' => 'Kota', 'postal_code' => '95512'],
        ['id' => 74,  'province_id' => 11, 'name' => 'Blitar', 'type' => 'Kabupaten', 'postal_code' =>'66171'],
        ['id' => 75,  'province_id' => 11, 'name' => 'Blitar', 'type' => 'Kota', 'postal_code' => '66124'],
        ['id' => 76,  'province_id' => 10, 'name' => 'Blora', 'type' => 'Kabupaten', 'postal_code' =>'58219'],
        ['id' => 77,  'province_id' => 7, 'name' => 'Boalemo', 'type' => 'Kabupaten', 'postal_code' =>'96319'],
        ['id' => 78,  'province_id' => 9, 'name' => 'Bogor', 'type' => 'Kabupaten', 'postal_code' =>'16911'],
        ['id' => 79,  'province_id' => 9, 'name' => 'Bogor', 'type' => 'Kota', 'postal_code' => '16119'],
        ['id' => 80,  'province_id' => 11, 'name' => 'Bojonegoro', 'type' => 'Kabupaten', 'postal_code' =>'62119'],
        ['id' => 81,  'province_id' => 31, 'name' => 'Bolaang Mongondow (Bolmong)', 'type' => 'Kabupaten', 'postal_code' =>'95755'],
        ['id' => 82,  'province_id' => 31, 'name' => 'Bolaang Mongondow Selatan', 'type' => 'Kabupaten', 'postal_code' =>'95774'],
        ['id' => 83,  'province_id' => 31, 'name' => 'Bolaang Mongondow Timur', 'type' => 'Kabupaten', 'postal_code' =>'95783'],
        ['id' => 84,  'province_id' => 31, 'name' => 'Bolaang Mongondow Utara', 'type' => 'Kabupaten', 'postal_code' =>'95765'],
        ['id' => 85,  'province_id' => 30, 'name' => 'Bombana', 'type' => 'Kabupaten', 'postal_code' =>'93771'],
        ['id' => 86,  'province_id' => 11, 'name' => 'Bondowoso', 'type' => 'Kabupaten', 'postal_code' =>'68219'],
        ['id' => 87,  'province_id' => 28, 'name' => 'Bone', 'type' => 'Kabupaten', 'postal_code' =>'92713'],
        ['id' => 88,  'province_id' => 7,  'name' => 'Bone Bolango', 'type' => 'Kabupaten', 'postal_code' =>'96511'],
        ['id' => 89,  'province_id' => 15, 'name' => 'Bontang', 'type' => 'Kota', 'postal_code' => '75313'],
        ['id' => 90,  'province_id' => 24, 'name' => 'Boven Digoel', 'type' => 'Kabupaten', 'postal_code' =>'99662'],
        ['id' => 91,  'province_id' => 10, 'name' => 'Boyolali', 'type' => 'Kabupaten', 'postal_code' =>'57312'],
        ['id' => 92,  'province_id' => 10, 'name' => 'Brebes', 'type' => 'Kabupaten', 'postal_code' =>'52212'],
        ['id' => 93,  'province_id' => 32, 'name' => 'Bukittinggi', 'type' => 'Kota', 'postal_code' => '26115'],
        ['id' => 94,  'province_id' => 1,  'name' => 'Buleleng', 'type' => 'Kabupaten', 'postal_code' =>'81111'],
        ['id' => 95,  'province_id' => 28, 'name' => 'Bulukumba', 'type' => 'Kabupaten', 'postal_code' =>'92511'],
        ['id' => 96,  'province_id' => 16, 'name' => 'Bulungan (Bulongan)', 'type' => 'Kabupaten', 'postal_code' =>'77211'],
        ['id' => 97,  'province_id' => 8,  'name' => 'Bungo', 'type' => 'Kabupaten', 'postal_code' =>'37216'],
        ['id' => 98,  'province_id' => 29, 'name' => 'Buol', 'type' => 'Kabupaten', 'postal_code' =>'94564'],
        ['id' => 99,  'province_id' => 19, 'name' => 'Buru', 'type' => 'Kabupaten', 'postal_code' =>'97371'],
        ['id' => 100, 'province_id' =>  19,'name' =>  'Buru Selatan', 'type' => 'Kabupaten', 'postal_code' =>'97351'],
        ['id' => 101, 'province_id' =>  30,'name' =>  'Buton', 'type' => 'Kabupaten', 'postal_code' =>'93754'],
        ['id' => 102, 'province_id' =>  30,'name' =>  'Buton Utara', 'type' => 'Kabupaten', 'postal_code' =>'93745'],
        ['id' => 103, 'province_id' =>  9, 'name' => 'Ciamis', 'type' => 'Kabupaten', 'postal_code' =>'46211'],
        ['id' => 104, 'province_id' =>  9, 'name' => 'Cianjur', 'type' => 'Kabupaten', 'postal_code' =>'43217'],
        ['id' => 105, 'province_id' =>  10,'name' =>  'Cilacap', 'type' => 'Kabupaten', 'postal_code' =>'53211'],
        ['id' => 106, 'province_id' =>  3, 'name' => 'Cilegon', 'type' => 'Kota', 'postal_code' => '42417'],
        ['id' => 107, 'province_id' =>  9, 'name' => 'Cimahi', 'type' => 'Kota', 'postal_code' => '40512'],
        ['id' => 108, 'province_id' =>  9, 'name' => 'Cirebon', 'type' => 'Kabupaten', 'postal_code' =>'45611'],
        ['id' => 109, 'province_id' =>  9, 'name' => 'Cirebon', 'type' => 'Kota', 'postal_code' => '45116'],
        ['id' => 110, 'province_id' =>  34,'name' =>  'Dairi', 'type' => 'Kabupaten', 'postal_code' =>'22211'],
        ['id' => 111, 'province_id' =>  24,'name' =>  'Deiyai (Deliyai)', 'type' => 'Kabupaten', 'postal_code' =>'98784'],
        ['id' => 112, 'province_id' =>  34,'name' =>  'Deli Serdang', 'type' => 'Kabupaten', 'postal_code' =>'20511'],
        ['id' => 113, 'province_id' =>  10,'name' =>  'Demak', 'type' => 'Kabupaten', 'postal_code' =>'59519'],
        ['id' => 114, 'province_id' =>  1, 'name' => 'Denpasar', 'type' => 'Kota', 'postal_code' => '80227'],
        ['id' => 115, 'province_id' =>  9, 'name' => 'Depok', 'type' => 'Kota', 'postal_code' => '16416'],
        ['id' => 116, 'province_id' =>  32,'name' =>  'Dharmasraya', 'type' => 'Kabupaten', 'postal_code' =>'27612'],
        ['id' => 117, 'province_id' =>  24,'name' =>  'Dogiyai', 'type' => 'Kabupaten', 'postal_code' =>'98866'],
        ['id' => 118, 'province_id' =>  22,'name' =>  'Dompu', 'type' => 'Kabupaten', 'postal_code' =>'84217'],
        ['id' => 119, 'province_id' =>  29,'name' =>  'Donggala', 'type' => 'Kabupaten', 'postal_code' =>'94341'],
        ['id' => 120, 'province_id' =>  26,'name' =>  'Dumai', 'type' => 'Kota', 'postal_code' => '28811'],
        ['id' => 121, 'province_id' =>  33,'name' =>  'Empat Lawang', 'type' => 'Kabupaten', 'postal_code' =>'31811'],
        ['id' => 122, 'province_id' =>  23,'name' =>  'Ende', 'type' => 'Kabupaten', 'postal_code' =>'86351'],
        ['id' => 123, 'province_id' =>  28,'name' =>  'Enrekang', 'type' => 'Kabupaten', 'postal_code' =>'91719'],
        ['id' => 124, 'province_id' =>  25,'name' =>  'Fakfak', 'type' => 'Kabupaten', 'postal_code' =>'98651'],
        ['id' => 125, 'province_id' =>  23,'name' =>  'Flores Timur', 'type' => 'Kabupaten', 'postal_code' =>'86213'],
        ['id' => 126, 'province_id' =>  9, 'name' => 'Garut', 'type' => 'Kabupaten', 'postal_code' =>'44126'],
        ['id' => 127, 'province_id' =>  21,'name' =>  'Gayo Lues', 'type' => 'Kabupaten', 'postal_code' =>'24653'],
        ['id' => 128, 'province_id' =>  1, 'name' => 'Gianyar', 'type' => 'Kabupaten', 'postal_code' =>'80519'],
        ['id' => 129, 'province_id' =>  7, 'name' => 'Gorontalo', 'type' => 'Kabupaten', 'postal_code' =>'96218'],
        ['id' => 130, 'province_id' =>  7, 'name' => 'Gorontalo', 'type' => 'Kota', 'postal_code' => '96115'],
        ['id' => 131, 'province_id' =>  7, 'name' => 'Gorontalo Utara', 'type' => 'Kabupaten', 'postal_code' =>'96611'],
        ['id' => 132, 'province_id' =>  28,'name' =>  'Gowa', 'type' => 'Kabupaten', 'postal_code' =>'92111'],
        ['id' => 133, 'province_id' =>  11,'name' =>  'Gresik', 'type' => 'Kabupaten', 'postal_code' =>'61115'],
        ['id' => 134, 'province_id' =>  10,'name' =>  'Grobogan', 'type' => 'Kabupaten', 'postal_code' =>'58111'],
        ['id' => 135, 'province_id' =>  5, 'name' => 'Gunung Kidul', 'type' => 'Kabupaten', 'postal_code' =>'55812'],
        ['id' => 136, 'province_id' =>  14,'name' =>  'Gunung Mas', 'type' => 'Kabupaten', 'postal_code' =>'74511'],
        ['id' => 137, 'province_id' =>  34,'name' =>  'Gunungsitoli', 'type' => 'Kota', 'postal_code' => '22813'],
        ['id' => 138, 'province_id' =>  20,'name' =>  'Halmahera Barat', 'type' => 'Kabupaten', 'postal_code' =>'97757'],
        ['id' => 139, 'province_id' =>  20,'name' =>  'Halmahera Selatan', 'type' => 'Kabupaten', 'postal_code' =>'97911'],
        ['id' => 140, 'province_id' =>  20,'name' =>  'Halmahera Tengah', 'type' => 'Kabupaten', 'postal_code' =>'97853'],
        ['id' => 141, 'province_id' =>  20,'name' =>  'Halmahera Timur', 'type' => 'Kabupaten', 'postal_code' =>'97862'],
        ['id' => 142, 'province_id' =>  20,'name' =>  'Halmahera Utara', 'type' => 'Kabupaten', 'postal_code' =>'97762'],
        ['id' => 143, 'province_id' =>  13,'name' =>  'Hulu Sungai Selatan', 'type' => 'Kabupaten', 'postal_code' =>'71212'],
        ['id' => 144, 'province_id' =>  13,'name' =>  'Hulu Sungai Tengah', 'type' => 'Kabupaten', 'postal_code' =>'71313'],
        ['id' => 145, 'province_id' =>  13,'name' =>  'Hulu Sungai Utara', 'type' => 'Kabupaten', 'postal_code' =>'71419'],
        ['id' => 146, 'province_id' =>  34,'name' =>  'Humbang Hasundutan', 'type' => 'Kabupaten', 'postal_code' =>'22457'],
        ['id' => 147, 'province_id' =>  26,'name' =>  'Indragiri Hilir', 'type' => 'Kabupaten', 'postal_code' =>'29212'],
        ['id' => 148, 'province_id' =>  26,'name' =>  'Indragiri Hulu', 'type' => 'Kabupaten', 'postal_code' =>'29319'],
        ['id' => 149, 'province_id' =>  9, 'name' => 'Indramayu', 'type' => 'Kabupaten', 'postal_code' =>'45214'],
        ['id' => 150, 'province_id' =>  24,'name' =>  'Intan Jaya', 'type' => 'Kabupaten', 'postal_code' =>'98771'],
        ['id' => 151, 'province_id' =>  6, 'name' => 'Jakarta Barat', 'type' => 'Kota', 'postal_code' => '11220'],
        ['id' => 152, 'province_id' =>  6, 'name' => 'Jakarta Pusat', 'type' => 'Kota', 'postal_code' => '10540'],
        ['id' => 153, 'province_id' =>  6, 'name' => 'Jakarta Selatan', 'type' => 'Kota', 'postal_code' => '12230'],
        ['id' => 154, 'province_id' =>  6, 'name' => 'Jakarta Timur', 'type' => 'Kota', 'postal_code' => '13330'],
        ['id' => 155, 'province_id' =>  6, 'name' => 'Jakarta Utara', 'type' => 'Kota', 'postal_code' => '14140'],
        ['id' => 156, 'province_id' =>  8, 'name' => 'Jambi', 'type' => 'Kota', 'postal_code' => '36111'],
        ['id' => 157, 'province_id' =>  24,'name' =>  'Jayapura', 'type' => 'Kabupaten', 'postal_code' =>'99352'],
        ['id' => 158, 'province_id' =>  24,'name' =>  'Jayapura', 'type' => 'Kota', 'postal_code' => '99114'],
        ['id' => 159, 'province_id' =>  24,'name' =>  'Jayawijaya', 'type' => 'Kabupaten', 'postal_code' =>'99511'],
        ['id' => 160, 'province_id' =>  11,'name' =>  'Jember', 'type' => 'Kabupaten', 'postal_code' =>'68113'],
        ['id' => 161, 'province_id' =>  1, 'name' => 'Jembrana', 'type' => 'Kabupaten', 'postal_code' =>'82251'],
        ['id' => 162, 'province_id' =>  28,'name' =>  'Jeneponto', 'type' => 'Kabupaten', 'postal_code' =>'92319'],
        ['id' => 163, 'province_id' =>  10,'name' =>  'Jepara', 'type' => 'Kabupaten', 'postal_code' =>'59419'],
        ['id' => 164, 'province_id' =>  11,'name' =>  'Jombang', 'type' => 'Kabupaten', 'postal_code' =>'61415'],
        ['id' => 165, 'province_id' =>  25,'name' =>  'Kaimana', 'type' => 'Kabupaten', 'postal_code' =>'98671'],
        ['id' => 166, 'province_id' =>  26,'name' =>  'Kampar', 'type' => 'Kabupaten', 'postal_code' =>'28411'],
        ['id' => 167, 'province_id' =>  14,'name' =>  'Kapuas', 'type' => 'Kabupaten', 'postal_code' =>'73583'],
        ['id' => 168, 'province_id' =>  12,'name' =>  'Kapuas Hulu', 'type' => 'Kabupaten', 'postal_code' =>'78719'],
        ['id' => 169, 'province_id' =>  10,'name' =>  'Karanganyar', 'type' => 'Kabupaten', 'postal_code' =>'57718'],
        ['id' => 170, 'province_id' =>  1, 'name' => 'Karangasem', 'type' => 'Kabupaten', 'postal_code' =>'80819'],
        ['id' => 171, 'province_id' =>  9, 'name' => 'Karawang', 'type' => 'Kabupaten', 'postal_code' =>'41311'],
        ['id' => 172, 'province_id' =>  17,'name' =>  'Karimun', 'type' => 'Kabupaten', 'postal_code' =>'29611'],
        ['id' => 173, 'province_id' =>  34,'name' =>  'Karo', 'type' => 'Kabupaten', 'postal_code' =>'22119'],
        ['id' => 174, 'province_id' =>  14,'name' =>  'Katingan', 'type' => 'Kabupaten', 'postal_code' =>'74411'],
        ['id' => 175, 'province_id' =>  4, 'name' => 'Kaur', 'type' => 'Kabupaten', 'postal_code' =>'38911'],
        ['id' => 176, 'province_id' =>  12,'name' =>  'Kayong Utara', 'type' => 'Kabupaten', 'postal_code' =>'78852'],
        ['id' => 177, 'province_id' =>  10,'name' =>  'Kebumen', 'type' => 'Kabupaten', 'postal_code' =>'54319'],
        ['id' => 178, 'province_id' =>  11,'name' =>  'Kediri', 'type' => 'Kabupaten', 'postal_code' =>'64184'],
        ['id' => 179, 'province_id' =>  11,'name' =>  'Kediri', 'type' => 'Kota', 'postal_code' => '64125'],
        ['id' => 180, 'province_id' =>  24,'name' =>  'Keerom', 'type' => 'Kabupaten', 'postal_code' =>'99461'],
        ['id' => 181, 'province_id' =>  10,'name' =>  'Kendal', 'type' => 'Kabupaten', 'postal_code' =>'51314'],
        ['id' => 182, 'province_id' =>  30,'name' =>  'Kendari', 'type' => 'Kota', 'postal_code' => '93126'],
        ['id' => 183, 'province_id' =>  4, 'name' => 'Kepahiang', 'type' => 'Kabupaten', 'postal_code' =>'39319'],
        ['id' => 184, 'province_id' =>  17,'name' =>  'Kepulauan Anambas', 'type' => 'Kabupaten', 'postal_code' =>'29991'],
        ['id' => 185, 'province_id' =>  19,'name' =>  'Kepulauan Aru', 'type' => 'Kabupaten', 'postal_code' =>'97681'],
        ['id' => 186, 'province_id' =>  32,'name' =>  'Kepulauan Mentawai', 'type' => 'Kabupaten', 'postal_code' =>'25771'],
        ['id' => 187, 'province_id' =>  26,'name' =>  'Kepulauan Meranti', 'type' => 'Kabupaten', 'postal_code' =>'28791'],
        ['id' => 188, 'province_id' =>  31,'name' =>  'Kepulauan Sangihe', 'type' => 'Kabupaten', 'postal_code' =>'95819'],
        ['id' => 189, 'province_id' =>  6, 'name' => 'Kepulauan Seribu', 'type' => 'Kabupaten', 'postal_code' =>'14550'],
        ['id' => 190, 'province_id' =>  31,'name' =>  'Kepulauan Siau Tagulandang Biaro (Sitaro)', 'type' => 'Kabupaten', 'postal_code' =>'95862'],
        ['id' => 191, 'province_id' =>  20,'name' =>  'Kepulauan Sula', 'type' => 'Kabupaten', 'postal_code' =>'97995'],
        ['id' => 192, 'province_id' =>  31,'name' =>  'Kepulauan Talaud', 'type' => 'Kabupaten', 'postal_code' =>'95885'],
        ['id' => 193, 'province_id' =>  24,'name' =>  'Kepulauan Yapen (Yapen Waropen)', 'type' => 'Kabupaten', 'postal_code' =>'98211'],
        ['id' => 194, 'province_id' =>  8, 'name' => 'Kerinci', 'type' => 'Kabupaten', 'postal_code' =>'37167'],
        ['id' => 195, 'province_id' =>  12,'name' =>  'Ketapang', 'type' => 'Kabupaten', 'postal_code' =>'78874'],
        ['id' => 196, 'province_id' =>  10,'name' =>  'Klaten', 'type' => 'Kabupaten', 'postal_code' =>'57411'],
        ['id' => 197, 'province_id' =>  1, 'name' => 'Klungkung', 'type' => 'Kabupaten', 'postal_code' =>'80719'],
        ['id' => 198, 'province_id' =>  30,'name' =>  'Kolaka', 'type' => 'Kabupaten', 'postal_code' =>'93511'],
        ['id' => 199, 'province_id' =>  30,'name' =>  'Kolaka Utara', 'type' => 'Kabupaten', 'postal_code' =>'93911'],
        ['id' => 200, 'province_id' =>  30,'name' =>  'Konawe', 'type' => 'Kabupaten', 'postal_code' =>'93411'],
        ['id' => 201, 'province_id' =>  30,'name' =>  'Konawe Selatan', 'type' => 'Kabupaten', 'postal_code' =>'93811'],
        ['id' => 202, 'province_id' =>  30,'name' =>  'Konawe Utara', 'type' => 'Kabupaten', 'postal_code' =>'93311'],
        ['id' => 203, 'province_id' =>  13,'name' =>   'Kotabaru', 'type' => 'Kabupaten', 'postal_code' =>'72119'],
        ['id' => 204, 'province_id' =>  31,'name' =>   'Kotamobagu', 'type' => 'Kota', 'postal_code' => '95711'],
        ['id' => 205, 'province_id' =>  14,'name' =>   'Kotawaringin Barat', 'type' => 'Kabupaten', 'postal_code' =>'74119'],
        ['id' => 206, 'province_id' =>  14,'name' =>  'Kotawaringin Timur', 'type' => 'Kabupaten', 'postal_code' =>'74364'],
        ['id' => 207, 'province_id' =>  26,'name' =>  'Kuantan Singingi', 'type' => 'Kabupaten', 'postal_code' =>'29519'],
        ['id' => 208, 'province_id' =>  12,'name' =>  'Kubu Raya', 'type' => 'Kabupaten', 'postal_code' =>'78311'],
        ['id' => 209, 'province_id' =>  10,'name' =>  'Kudus', 'type' => 'Kabupaten', 'postal_code' =>'59311'],
        ['id' => 210, 'province_id' =>  5, 'name' => 'Kulon Progo', 'type' => 'Kabupaten', 'postal_code' =>'55611'],
        ['id' => 211, 'province_id' =>  9, 'name' => 'Kuningan', 'type' => 'Kabupaten', 'postal_code' =>'45511'],
        ['id' => 212, 'province_id' =>  23,'name' =>  'Kupang', 'type' => 'Kabupaten', 'postal_code' =>'85362'],
        ['id' => 213, 'province_id' =>  23,'name' =>  'Kupang', 'type' => 'Kota', 'postal_code' => '85119'],
        ['id' => 214, 'province_id' =>  15,'name' =>  'Kutai Barat', 'type' => 'Kabupaten', 'postal_code' =>'75711'],
        ['id' => 215, 'province_id' =>  15,'name' =>  'Kutai Kartanegara', 'type' => 'Kabupaten', 'postal_code' =>'75511'],
        ['id' => 216, 'province_id' =>  15,'name' =>  'Kutai Timur', 'type' => 'Kabupaten', 'postal_code' =>'75611'],
        ['id' => 217, 'province_id' =>  34,'name' =>  'Labuhan Batu', 'type' => 'Kabupaten', 'postal_code' =>'21412'],
        ['id' => 218, 'province_id' =>  34,'name' =>  'Labuhan Batu Selatan', 'type' => 'Kabupaten', 'postal_code' =>'21511'],
        ['id' => 219, 'province_id' =>  34,'name' =>  'Labuhan Batu Utara', 'type' => 'Kabupaten', 'postal_code' =>'21711'],
        ['id' => 220, 'province_id' =>  33,'name' =>  'Lahat', 'type' => 'Kabupaten', 'postal_code' =>'31419'],
        ['id' => 221, 'province_id' =>  14,'name' =>  'Lamandau', 'type' => 'Kabupaten', 'postal_code' =>'74611'],
        ['id' => 222, 'province_id' =>  11,'name' =>  'Lamongan', 'type' => 'Kabupaten', 'postal_code' =>'64125'],
        ['id' => 223, 'province_id' =>  18,'name' =>  'Lampung Barat', 'type' => 'Kabupaten', 'postal_code' =>'34814'],
        ['id' => 224, 'province_id' =>  18,'name' =>  'Lampung Selatan', 'type' => 'Kabupaten', 'postal_code' =>'35511'],
        ['id' => 225, 'province_id' =>  18,'name' =>  'Lampung Tengah', 'type' => 'Kabupaten', 'postal_code' =>'34212'],
        ['id' => 226, 'province_id' =>  18,'name' =>  'Lampung Timur', 'type' => 'Kabupaten', 'postal_code' =>'34319'],
        ['id' => 227, 'province_id' =>  18,'name' =>  'Lampung Utara', 'type' => 'Kabupaten', 'postal_code' =>'34516'],
        ['id' => 228, 'province_id' =>  12,'name' =>  'Landak', 'type' => 'Kabupaten', 'postal_code' =>'78319'],
        ['id' => 229, 'province_id' =>  34,'name' =>  'Langkat', 'type' => 'Kabupaten', 'postal_code' =>'20811'],
        ['id' => 230, 'province_id' =>  21,'name' =>  'Langsa', 'type' => 'Kota', 'postal_code' => '24412'],
        ['id' => 231, 'province_id' =>  24,'name' =>  'Lanny Jaya', 'type' => 'Kabupaten', 'postal_code' =>'99531'],
        ['id' => 232, 'province_id' =>  3, 'name' => 'Lebak', 'type' => 'Kabupaten', 'postal_code' =>'42319'],
        ['id' => 233, 'province_id' =>  4, 'name' => 'Lebong', 'type' => 'Kabupaten', 'postal_code' =>'39264'],
        ['id' => 234, 'province_id' =>  23,'name' =>  'Lembata', 'type' => 'Kabupaten', 'postal_code' =>'86611'],
        ['id' => 235, 'province_id' =>  21,'name' =>  'Lhokseumawe', 'type' => 'Kota', 'postal_code' => '24352'],
        ['id' => 236, 'province_id' =>  32,'name' =>  'Lima Puluh Koto Kota',  'type' => 'Kabupaten', 'postal_code' =>'26671'],
        ['id' => 237, 'province_id' =>  17,'name' =>  'Lingga', 'type' => 'Kabupaten', 'postal_code' =>'29811'],
        ['id' => 238, 'province_id' =>  22,'name' =>  'Lombok Barat', 'type' => 'Kabupaten', 'postal_code' =>'83311'],
        ['id' => 239, 'province_id' =>  22,'name' =>  'Lombok Tengah', 'type' => 'Kabupaten', 'postal_code' =>'83511'],
        ['id' => 240, 'province_id' =>  22,'name' =>  'Lombok Timur', 'type' => 'Kabupaten', 'postal_code' =>'83612'],
        ['id' => 241, 'province_id' =>  22,'name' =>  'Lombok Utara', 'type' => 'Kabupaten', 'postal_code' =>'83711'],
        ['id' => 242, 'province_id' =>  33,'name' =>  'Lubuk Linggau', 'type' => 'Kota', 'postal_code' => '31614'],
        ['id' => 243, 'province_id' =>  11,'name' =>  'Lumajang', 'type' => 'Kabupaten', 'postal_code' =>'67319'],
        ['id' => 244, 'province_id' =>  28,'name' =>  'Luwu', 'type' => 'Kabupaten', 'postal_code' =>'91994'],
        ['id' => 245, 'province_id' =>  28,'name' =>  'Luwu Timur', 'type' => 'Kabupaten', 'postal_code' =>'92981'],
        ['id' => 246, 'province_id' =>  28,'name' =>  'Luwu Utara', 'type' => 'Kabupaten', 'postal_code' =>'92911'],
        ['id' => 247, 'province_id' =>  11,'name' =>  'Madiun', 'type' => 'Kabupaten', 'postal_code' =>'63153'],
        ['id' => 248, 'province_id' =>  11,'name' =>  'Madiun', 'type' => 'Kota', 'postal_code' => '63122'],
        ['id' => 249, 'province_id' =>  10,'name' =>  'Magelang', 'type' => 'Kabupaten', 'postal_code' =>'56519'],
        ['id' => 250, 'province_id' =>  10,'name' =>  'Magelang', 'type' => 'Kota', 'postal_code' => '56133'],
        ['id' => 251, 'province_id' =>  11,'name' =>  'Magetan', 'type' => 'Kabupaten', 'postal_code' =>'63314'],
        ['id' => 252, 'province_id' =>  9, 'name' => 'Majalengka', 'type' => 'Kabupaten', 'postal_code' =>'45412'],
        ['id' => 253, 'province_id' =>  27,'name' =>  'Majene', 'type' => 'Kabupaten', 'postal_code' =>'91411'],
        ['id' => 254, 'province_id' =>  28,'name' =>  'Makassar', 'type' => 'Kota', 'postal_code' => '90111'],
        ['id' => 255, 'province_id' =>  11,'name' =>  'Malang', 'type' => 'Kabupaten', 'postal_code' =>'65163'],
        ['id' => 256, 'province_id' =>  11,'name' =>  'Malang', 'type' => 'Kota', 'postal_code' => '65112'],
        ['id' => 257, 'province_id' =>  16,'name' =>  'Malinau', 'type' => 'Kabupaten', 'postal_code' =>'77511'],
        ['id' => 258, 'province_id' =>  19,'name' =>  'Maluku Barat Daya', 'type' => 'Kabupaten', 'postal_code' =>'97451'],
        ['id' => 259, 'province_id' =>  19,'name' =>  'Maluku Tengah', 'type' => 'Kabupaten', 'postal_code' =>'97513'],
        ['id' => 260, 'province_id' =>  19,'name' =>  'Maluku Tenggara', 'type' => 'Kabupaten', 'postal_code' =>'97651'],
        ['id' => 261, 'province_id' =>  19,'name' =>  'Maluku Tenggara Barat', 'type' => 'Kabupaten', 'postal_code' =>'97465'],
        ['id' => 262, 'province_id' =>  27,'name' =>  'Mamasa', 'type' => 'Kabupaten', 'postal_code' =>'91362'],
        ['id' => 263, 'province_id' =>  24,'name' =>  'Mamberamo Raya', 'type' => 'Kabupaten', 'postal_code' =>'99381'],
        ['id' => 264, 'province_id' =>  24,'name' =>  'Mamberamo Tengah', 'type' => 'Kabupaten', 'postal_code' =>'99553'],
        ['id' => 265, 'province_id' =>  27,'name' =>  'Mamuju', 'type' => 'Kabupaten', 'postal_code' =>'91519'],
        ['id' => 266, 'province_id' =>  27,'name' =>  'Mamuju Utara', 'type' => 'Kabupaten', 'postal_code' =>'91571'],
        ['id' => 267, 'province_id' =>  31,'name' =>  'Manado', 'type' => 'Kota', 'postal_code' => '95247'],
        ['id' => 268, 'province_id' =>  34,'name' =>  'Mandailing Natal', 'type' => 'Kabupaten', 'postal_code' =>'22916'],
        ['id' => 269, 'province_id' =>  23,'name' =>  'Manggarai', 'type' => 'Kabupaten', 'postal_code' =>'86551'],
        ['id' => 270, 'province_id' =>  23,'name' =>  'Manggarai Barat', 'type' => 'Kabupaten', 'postal_code' =>'86711'],
        ['id' => 271, 'province_id' =>  23,'name' =>  'Manggarai Timur', 'type' => 'Kabupaten', 'postal_code' =>'86811'],
        ['id' => 272, 'province_id' =>  25,'name' =>  'Manokwari', 'type' => 'Kabupaten', 'postal_code' =>'98311'],
        ['id' => 273, 'province_id' =>  25,'name' =>  'Manokwari Selatan', 'type' => 'Kabupaten', 'postal_code' =>'98355'],
        ['id' => 274, 'province_id' =>  24,'name' =>  'Mappi', 'type' => 'Kabupaten', 'postal_code' =>'99853'],
        ['id' => 275, 'province_id' =>  28,'name' =>  'Maros', 'type' => 'Kabupaten', 'postal_code' =>'90511'],
        ['id' => 276, 'province_id' =>  22,'name' =>  'Mataram', 'type' => 'Kota', 'postal_code' => '83131'],
        ['id' => 277, 'province_id' =>  25,'name' =>  'Maybrat', 'type' => 'Kabupaten', 'postal_code' =>'98051'],
        ['id' => 278, 'province_id' =>  34,'name' =>  'Medan', 'type' => 'Kota', 'postal_code' => '20228'],
        ['id' => 279, 'province_id' =>  12,'name' =>  'Melawi', 'type' => 'Kabupaten', 'postal_code' =>'78619'],
        ['id' => 280, 'province_id' =>  8, 'name' => 'Merangin', 'type' => 'Kabupaten', 'postal_code' =>'37319'],
        ['id' => 281, 'province_id' =>  24,'name' =>  'Merauke', 'type' => 'Kabupaten', 'postal_code' =>'99613'],
        ['id' => 282, 'province_id' =>  18,'name' =>  'Mesuji', 'type' => 'Kabupaten', 'postal_code' =>'34911'],
        ['id' => 283, 'province_id' =>  18,'name' =>  'Metro', 'type' => 'Kota', 'postal_code' => '34111'],
        ['id' => 284, 'province_id' =>  24,'name' =>  'Mimika', 'type' => 'Kabupaten', 'postal_code' =>'99962'],
        ['id' => 285, 'province_id' =>  31,'name' =>  'Minahasa', 'type' => 'Kabupaten', 'postal_code' =>'95614'],
        ['id' => 286, 'province_id' =>  31,'name' =>  'Minahasa Selatan', 'type' => 'Kabupaten', 'postal_code' =>'95914'],
        ['id' => 287, 'province_id' =>  31,'name' =>  'Minahasa Tenggara', 'type' => 'Kabupaten', 'postal_code' =>'95995'],
        ['id' => 288, 'province_id' =>  31,'name' =>  'Minahasa Utara', 'type' => 'Kabupaten', 'postal_code' =>'95316'],
        ['id' => 289, 'province_id' =>  11,'name' =>  'Mojokerto', 'type' => 'Kabupaten', 'postal_code' =>'61382'],
        ['id' => 290, 'province_id' =>  11,'name' =>  'Mojokerto', 'type' => 'Kota', 'postal_code' => '61316'],
        ['id' => 291, 'province_id' =>  29,'name' =>  'Morowali', 'type' => 'Kabupaten', 'postal_code' =>'94911'],
        ['id' => 292, 'province_id' =>  33,'name' =>  'Muara Enim', 'type' => 'Kabupaten', 'postal_code' =>'31315'],
        ['id' => 293, 'province_id' =>  8, 'name' => 'Muaro Jambi', 'type' => 'Kabupaten', 'postal_code' =>'36311'],
        ['id' => 294, 'province_id' =>  4, 'name' => 'Muko Muko', 'type' => 'Kabupaten', 'postal_code' =>'38715'],
        ['id' => 295, 'province_id' =>  30,'name' =>  'Muna', 'type' => 'Kabupaten', 'postal_code' =>'93611'],
        ['id' => 296, 'province_id' =>  14,'name' =>  'Murung Raya', 'type' => 'Kabupaten', 'postal_code' =>'73911'],
        ['id' => 297, 'province_id' =>  33,'name' =>  'Musi Banyuasin', 'type' => 'Kabupaten', 'postal_code' =>'30719'],
        ['id' => 298, 'province_id' =>  33,'name' =>  'Musi Rawas', 'type' => 'Kabupaten', 'postal_code' =>'31661'],
        ['id' => 299, 'province_id' =>  24,'name' =>  'Nabire', 'type' => 'Kabupaten', 'postal_code' =>'98816'],
        ['id' => 300, 'province_id' =>  21,'name' =>  'Nagan Raya', 'type' => 'Kabupaten', 'postal_code' =>'23674'],
        ['id' => 301, 'province_id' =>  23,'name' =>  'Nagekeo', 'type' => 'Kabupaten', 'postal_code' =>'86911'],
        ['id' => 302, 'province_id' =>  17,'name' =>  'Natuna', 'type' => 'Kabupaten', 'postal_code' =>'29711'],
        ['id' => 303, 'province_id' =>  24,'name' =>  'Nduga', 'type' => 'Kabupaten', 'postal_code' =>'99541'],
        ['id' => 304, 'province_id' =>  23,'name' =>  'Ngada', 'type' => 'Kabupaten', 'postal_code' =>'86413'],
        ['id' => 305, 'province_id' =>  11,'name' =>  'Nganjuk', 'type' => 'Kabupaten', 'postal_code' =>'64414'],
        ['id' => 306, 'province_id' =>  11,'name' =>  'Ngawi', 'type' => 'Kabupaten', 'postal_code' =>'63219'],
        ['id' => 307, 'province_id' =>  34,'name' =>  'Nias', 'type' => 'Kabupaten', 'postal_code' =>'22876'],
        ['id' => 308, 'province_id' =>  34,'name' =>  'Nias Barat', 'type' => 'Kabupaten', 'postal_code' =>'22895'],
        ['id' => 309, 'province_id' =>  34,'name' =>  'Nias Selatan', 'type' => 'Kabupaten', 'postal_code' =>'22865'],
        ['id' => 310, 'province_id' =>  34,'name' =>  'Nias Utara', 'type' => 'Kabupaten', 'postal_code' =>'22856'],
        ['id' => 311, 'province_id' =>  16,'name' =>  'Nunukan', 'type' => 'Kabupaten', 'postal_code' =>'77421'],
        ['id' => 312, 'province_id' =>  33,'name' =>  'Ogan Ilir', 'type' => 'Kabupaten', 'postal_code' =>'30811'],
        ['id' => 313, 'province_id' =>  33,'name' =>  'Ogan Komering Ilir', 'type' => 'Kabupaten', 'postal_code' =>'30618'],
        ['id' => 314, 'province_id' =>  33,'name' =>  'Ogan Komering Ulu', 'type' => 'Kabupaten', 'postal_code' =>'32112'],
        ['id' => 315, 'province_id' =>  33,'name' =>  'Ogan Komering Ulu Selatan', 'type' => 'Kabupaten', 'postal_code' =>'32211'],
        ['id' => 316, 'province_id' =>  33,'name' =>  'Ogan Komering Ulu Timur', 'type' => 'Kabupaten', 'postal_code' =>'32312'],
        ['id' => 317, 'province_id' =>  11,'name' =>  'Pacitan', 'type' => 'Kabupaten', 'postal_code' =>'63512'],
        ['id' => 318, 'province_id' =>  32,'name' =>  'Padang', 'type' => 'Kota', 'postal_code' => '25112'],
        ['id' => 319, 'province_id' =>  34,'name' =>  'Padang Lawas', 'type' => 'Kabupaten', 'postal_code' =>'22763'],
        ['id' => 320, 'province_id' =>  34,'name' =>  'Padang Lawas Utara', 'type' => 'Kabupaten', 'postal_code' =>'22753'],
        ['id' => 321, 'province_id' =>  32,'name' =>  'Padang Panjang', 'type' => 'Kota', 'postal_code' => '27122'],
        ['id' => 322, 'province_id' =>  32,'name' =>  'Padang Pariaman', 'type' => 'Kabupaten', 'postal_code' =>'25583'],
        ['id' => 323, 'province_id' =>  34,'name' =>  'Padang Sidempuan', 'type' => 'Kota', 'postal_code' => '22727'],
        ['id' => 324, 'province_id' =>  33,'name' =>  'Pagar Alam', 'type' => 'Kota', 'postal_code' => '31512'],
        ['id' => 325, 'province_id' =>  34,'name' =>  'Pakpak Bharat', 'type' => 'Kabupaten', 'postal_code' =>'22272'],
        ['id' => 326, 'province_id' =>  14,'name' =>  'Palangka Raya', 'type' => 'Kota', 'postal_code' => '73112'],
        ['id' => 327, 'province_id' =>  33,'name' =>  'Palembang', 'type' => 'Kota', 'postal_code' => '30111'],
        ['id' => 328, 'province_id' =>  28,'name' =>  'Palopo', 'type' => 'Kota', 'postal_code' => '91911'],
        ['id' => 329, 'province_id' =>  29,'name' =>  'Palu', 'type' => 'Kota', 'postal_code' => '94111'],
        ['id' => 330, 'province_id' =>  11,'name' =>  'Pamekasan', 'type' => 'Kabupaten', 'postal_code' =>'69319'],
        ['id' => 331, 'province_id' =>  3, 'name' => 'Pandeglang', 'type' => 'Kabupaten', 'postal_code' =>'42212'],
        ['id' => 332, 'province_id' =>  9, 'name' => 'Pangandaran', 'type' => 'Kabupaten', 'postal_code' =>'46511'],
        ['id' => 333, 'province_id' =>  28,'name' =>  'Pangkajene Kepulauan', 'type' => 'Kabupaten', 'postal_code' =>'90611'],
        ['id' => 334, 'province_id' =>  2, 'name' => 'Pangkal Pinang', 'type' => 'Kota', 'postal_code' => '33115'],
        ['id' => 335, 'province_id' =>  24,'name' =>  'Paniai', 'type' => 'Kabupaten', 'postal_code' =>'98765'],
        ['id' => 336, 'province_id' =>  28,'name' =>  'Parepare', 'type' => 'Kota', 'postal_code' => '91123'],
        ['id' => 337, 'province_id' =>  32,'name' =>  'Pariaman', 'type' => 'Kota', 'postal_code' => '25511'],
        ['id' => 338, 'province_id' =>  29,'name' =>  'Parigi Moutong', 'type' => 'Kabupaten', 'postal_code' =>'94411'],
        ['id' => 339, 'province_id' =>  32,'name' =>  'Pasaman', 'type' => 'Kabupaten', 'postal_code' =>'26318'],
        ['id' => 340, 'province_id' =>  32,'name' =>  'Pasaman Barat', 'type' => 'Kabupaten', 'postal_code' =>'26511'],
        ['id' => 341, 'province_id' =>  15,'name' =>  'Paser', 'type' => 'Kabupaten', 'postal_code' =>'76211'],
        ['id' => 342, 'province_id' =>  11,'name' =>  'Pasuruan', 'type' => 'Kabupaten', 'postal_code' =>'67153'],
        ['id' => 343, 'province_id' =>  11,'name' =>  'Pasuruan', 'type' => 'Kota', 'postal_code' => '67118'],
        ['id' => 344, 'province_id' =>  10,'name' =>  'Pati', 'type' => 'Kabupaten', 'postal_code' =>'59114'],
        ['id' => 345, 'province_id' =>  32,'name' =>  'Payakumbuh', 'type' => 'Kota', 'postal_code' => '26213'],
        ['id' => 346, 'province_id' =>  25,'name' =>  'Pegunungan Arfak', 'type' => 'Kabupaten', 'postal_code' =>'98354'],
        ['id' => 347, 'province_id' =>  24,'name' =>  'Pegunungan Bintang', 'type' => 'Kabupaten', 'postal_code' =>'99573'],
        ['id' => 348, 'province_id' =>  10,'name' =>  'Pekalongan', 'type' => 'Kabupaten', 'postal_code' =>'51161'],
        ['id' => 349, 'province_id' =>  10,'name' =>  'Pekalongan', 'type' => 'Kota', 'postal_code' => '51122'],
        ['id' => 350, 'province_id' =>  26,'name' =>  'Pekanbaru', 'type' => 'Kota', 'postal_code' => '28112'],
        ['id' => 351, 'province_id' =>  26,'name' =>  'Pelalawan', 'type' => 'Kabupaten', 'postal_code' =>'28311'],
        ['id' => 352, 'province_id' =>  10,'name' =>  'Pemalang', 'type' => 'Kabupaten', 'postal_code' =>'52319'],
        ['id' => 353, 'province_id' =>  34,'name' =>  'Pematang Siantar', 'type' => 'Kota', 'postal_code' => '21126'],
        ['id' => 354, 'province_id' =>  15,'name' =>  'Penajam Paser Utara', 'type' => 'Kabupaten', 'postal_code' =>'76311'],
        ['id' => 355, 'province_id' =>  18,'name' =>  'Pesawaran', 'type' => 'Kabupaten', 'postal_code' =>'35312'],
        ['id' => 356, 'province_id' =>  18,'name' =>  'Pesisir Barat', 'type' => 'Kabupaten', 'postal_code' =>'35974'],
        ['id' => 357, 'province_id' =>  32,'name' =>  'Pesisir Selatan', 'type' => 'Kabupaten', 'postal_code' =>'25611'],
        ['id' => 358, 'province_id' =>  21,'name' =>  'Pidie', 'type' => 'Kabupaten', 'postal_code' =>'24116'],
        ['id' => 359, 'province_id' =>  21,'name' =>  'Pidie Jaya', 'type' => 'Kabupaten', 'postal_code' =>'24186'],
        ['id' => 360, 'province_id' =>  28,'name' =>  'Pinrang', 'type' => 'Kabupaten', 'postal_code' =>'91251'],
        ['id' => 361, 'province_id' =>  7, 'name' => 'Pohuwato', 'type' => 'Kabupaten', 'postal_code' =>'96419'],
        ['id' => 362, 'province_id' =>  27,'name' =>  'Polewali Mandar', 'type' => 'Kabupaten', 'postal_code' =>'91311'],
        ['id' => 363, 'province_id' =>  11,'name' =>  'Ponorogo', 'type' => 'Kabupaten', 'postal_code' =>'63411'],
        ['id' => 364, 'province_id' =>  12,'name' =>  'Pontianak', 'type' => 'Kabupaten', 'postal_code' =>'78971'],
        ['id' => 365, 'province_id' =>  12,'name' =>  'Pontianak', 'type' => 'Kota', 'postal_code' => '78112'],
        ['id' => 366, 'province_id' =>  29,'name' =>  'Poso', 'type' => 'Kabupaten', 'postal_code' =>'94615'],
        ['id' => 367, 'province_id' =>  33,'name' =>  'Prabumulih', 'type' => 'Kota', 'postal_code' => '31121'],
        ['id' => 368, 'province_id' =>  18,'name' =>  'Pringsewu', 'type' => 'Kabupaten', 'postal_code' =>'35719'],
        ['id' => 369, 'province_id' =>  11,'name' =>  'Probolinggo', 'type' => 'Kabupaten', 'postal_code' =>'67282'],
        ['id' => 370, 'province_id' =>  11,'name' =>  'Probolinggo', 'type' => 'Kota', 'postal_code' => '67215'],
        ['id' => 371, 'province_id' =>  14,'name' =>  'Pulang Pisau', 'type' => 'Kabupaten', 'postal_code' =>'74811'],
        ['id' => 372, 'province_id' =>  20,'name' =>  'Pulau Morotai', 'type' => 'Kabupaten', 'postal_code' =>'97771'],
        ['id' => 373, 'province_id' =>  24,'name' =>  'Puncak', 'type' => 'Kabupaten', 'postal_code' =>'98981'],
        ['id' => 374, 'province_id' =>  24,'name' =>  'Puncak Jaya', 'type' => 'Kabupaten', 'postal_code' =>'98979'],
        ['id' => 375, 'province_id' =>  10,'name' =>  'Purbalingga', 'type' => 'Kabupaten', 'postal_code' =>'53312'],
        ['id' => 376, 'province_id' =>  9, 'name' => 'Purwakarta', 'type' => 'Kabupaten', 'postal_code' =>'41119'],
        ['id' => 377, 'province_id' =>  10,'name' =>  'Purworejo', 'type' => 'Kabupaten', 'postal_code' =>'54111'],
        ['id' => 378, 'province_id' =>  25,'name' =>  'Raja Ampat', 'type' => 'Kabupaten', 'postal_code' =>'98489'],
        ['id' => 379, 'province_id' =>  4, 'name' => 'Rejang Lebong', 'type' => 'Kabupaten', 'postal_code' =>'39112'],
        ['id' => 380, 'province_id' =>  10,'name' =>  'Rembang', 'type' => 'Kabupaten', 'postal_code' =>'59219'],
        ['id' => 381, 'province_id' =>  26,'name' =>  'Rokan Hilir', 'type' => 'Kabupaten', 'postal_code' =>'28992'],
        ['id' => 382, 'province_id' =>  26,'name' =>  'Rokan Hulu', 'type' => 'Kabupaten', 'postal_code' =>'28511'],
        ['id' => 383, 'province_id' =>  23,'name' =>  'Rote Ndao', 'type' => 'Kabupaten', 'postal_code' =>'85982'],
        ['id' => 384, 'province_id' =>  21,'name' =>  'Sabang', 'type' => 'Kota', 'postal_code' => '23512'],
        ['id' => 385, 'province_id' =>  23,'name' =>  'Sabu Raijua', 'type' => 'Kabupaten', 'postal_code' =>'85391'],
        ['id' => 386, 'province_id' =>  10,'name' =>  'Salatiga', 'type' => 'Kota', 'postal_code' => '50711'],
        ['id' => 387, 'province_id' =>  15,'name' =>  'Samarinda', 'type' => 'Kota', 'postal_code' => '75133'],
        ['id' => 388, 'province_id' =>  12,'name' =>  'Sambas', 'type' => 'Kabupaten', 'postal_code' =>'79453'],
        ['id' => 389, 'province_id' =>  34,'name' =>  'Samosir', 'type' => 'Kabupaten', 'postal_code' =>'22392'],
        ['id' => 390, 'province_id' =>  11,'name' =>  'Sampang', 'type' => 'Kabupaten', 'postal_code' =>'69219'],
        ['id' => 391, 'province_id' =>  12,'name' =>  'Sanggau', 'type' => 'Kabupaten', 'postal_code' =>'78557'],
        ['id' => 392, 'province_id' =>  24,'name' =>  'Sarmi', 'type' => 'Kabupaten', 'postal_code' =>'99373'],
        ['id' => 393, 'province_id' =>  8, 'name' => 'Sarolangun', 'type' => 'Kabupaten', 'postal_code' =>'37419'],
        ['id' => 394, 'province_id' =>  32,'name' =>  'Sawah Lunto', 'type' => 'Kota', 'postal_code' => '27416'],
        ['id' => 395, 'province_id' =>  12,'name' =>  'Sekadau', 'type' => 'Kabupaten', 'postal_code' =>'79583'],
        ['id' => 396, 'province_id' =>  28,'name' =>  'Selayar (Kepulauan Selayar)', 'type' => 'Kabupaten', 'postal_code' =>'92812'],
        ['id' => 397, 'province_id' =>  4, 'name' => 'Seluma', 'type' => 'Kabupaten', 'postal_code' =>'38811'],
        ['id' => 398, 'province_id' =>  10,'name' =>  'Semarang', 'type' => 'Kabupaten', 'postal_code' =>'50511'],
        ['id' => 399, 'province_id' =>  10,'name' =>  'Semarang', 'type' => 'Kota', 'postal_code' => '50135'],
        ['id' => 400, 'province_id' =>  19,'name' =>  'Seram Bagian Barat', 'type' => 'Kabupaten', 'postal_code' =>'97561'],
        ['id' => 401, 'province_id' =>  19,'name' =>  'Seram Bagian Timur', 'type' => 'Kabupaten', 'postal_code' =>'97581'],
        ['id' => 402, 'province_id' =>  3, 'name' => 'Serang', 'type' => 'Kabupaten', 'postal_code' =>'42182'],
        ['id' => 403, 'province_id' =>  3, 'name' => 'Serang', 'type' => 'Kota', 'postal_code' => '42111'],
        ['id' => 404, 'province_id' =>  34,'name' =>  'Serdang Bedagai', 'type' => 'Kabupaten', 'postal_code' =>'20915'],
        ['id' => 405, 'province_id' =>  14,'name' =>  'Seruyan', 'type' => 'Kabupaten', 'postal_code' =>'74211'],
        ['id' => 406, 'province_id' =>  26,'name' =>  'Siak', 'type' => 'Kabupaten', 'postal_code' =>'28623'],
        ['id' => 407, 'province_id' =>  34,'name' =>  'Sibolga', 'type' => 'Kota', 'postal_code' => '22522'],
        ['id' => 408, 'province_id' =>  28,'name' =>  'Sidenreng Rappang/Rapang', 'type' => 'Kabupaten', 'postal_code' =>'91613'],
        ['id' => 409, 'province_id' =>  11,'name' =>  'Sidoarjo', 'type' => 'Kabupaten', 'postal_code' =>'61219'],
        ['id' => 410, 'province_id' =>  29,'name' =>  'Sigi', 'type' => 'Kabupaten', 'postal_code' =>'94364'],
        ['id' => 411, 'province_id' =>  32,'name' =>  'Sijunjung (Sawah Lunto Sijunjung)', 'type' => 'Kabupaten', 'postal_code' =>'27511'],
        ['id' => 412, 'province_id' =>  23,'name' =>  'Sikka', 'type' => 'Kabupaten', 'postal_code' =>'86121'],
        ['id' => 413, 'province_id' =>  34,'name' =>  'Simalungun', 'type' => 'Kabupaten', 'postal_code' =>'21162'],
        ['id' => 414, 'province_id' =>  21,'name' =>  'Simeulue', 'type' => 'Kabupaten', 'postal_code' =>'23891'],
        ['id' => 415, 'province_id' =>  12,'name' =>  'Singkawang', 'type' => 'Kota', 'postal_code' => '79117'],
        ['id' => 416, 'province_id' =>  28,'name' =>  'Sinjai', 'type' => 'Kabupaten', 'postal_code' =>'92615'],
        ['id' => 417, 'province_id' =>  12,'name' =>  'Sintang', 'type' => 'Kabupaten', 'postal_code' =>'78619'],
        ['id' => 418, 'province_id' =>  11,'name' =>  'Situbondo', 'type' => 'Kabupaten', 'postal_code' =>'68316'],
        ['id' => 419, 'province_id' =>  5, 'name' => 'Sleman', 'type' => 'Kabupaten', 'postal_code' =>'55513'],
        ['id' => 420, 'province_id' =>  32,'name' =>  'Solok', 'type' => 'Kabupaten', 'postal_code' =>'27365'],
        ['id' => 421, 'province_id' =>  32,'name' =>  'Solok', 'type' => 'Kota', 'postal_code' => '27315'],
        ['id' => 422, 'province_id' =>  32,'name' =>  'Solok Selatan', 'type' => 'Kabupaten', 'postal_code' =>'27779'],
        ['id' => 423, 'province_id' =>  28,'name' =>  'Soppeng', 'type' => 'Kabupaten', 'postal_code' =>'90812'],
        ['id' => 424, 'province_id' =>  25,'name' =>  'Sorong', 'type' => 'Kabupaten', 'postal_code' =>'98431'],
        ['id' => 425, 'province_id' =>  25,'name' =>  'Sorong', 'type' => 'Kota', 'postal_code' => '98411'],
        ['id' => 426, 'province_id' =>  25,'name' =>  'Sorong Selatan', 'type' => 'Kabupaten', 'postal_code' =>'98454'],
        ['id' => 427, 'province_id' =>  10,'name' =>  'Sragen', 'type' => 'Kabupaten', 'postal_code' =>'57211'],
        ['id' => 428, 'province_id' =>  9, 'name' => 'Subang', 'type' => 'Kabupaten', 'postal_code' =>'41215'],
        ['id' => 429, 'province_id' =>  21,'name' =>  'Subulussalam', 'type' => 'Kota', 'postal_code' => '24882'],
        ['id' => 430, 'province_id' =>  9, 'name' => 'Sukabumi', 'type' => 'Kabupaten', 'postal_code' =>'43311'],
        ['id' => 431, 'province_id' =>  9, 'name' => 'Sukabumi', 'type' => 'Kota', 'postal_code' => '43114'],
        ['id' => 432, 'province_id' =>  14,'name' =>  'Sukamara', 'type' => 'Kabupaten', 'postal_code' =>'74712'],
        ['id' => 433, 'province_id' =>  10,'name' =>  'Sukoharjo', 'type' => 'Kabupaten', 'postal_code' =>'57514'],
        ['id' => 434, 'province_id' =>  23,'name' =>  'Sumba Barat', 'type' => 'Kabupaten', 'postal_code' =>'87219'],
        ['id' => 435, 'province_id' =>  23,'name' =>  'Sumba Barat Daya', 'type' => 'Kabupaten', 'postal_code' =>'87453'],
        ['id' => 436, 'province_id' =>  23,'name' =>  'Sumba Tengah', 'type' => 'Kabupaten', 'postal_code' =>'87358'],
        ['id' => 437, 'province_id' =>  23,'name' =>  'Sumba Timur', 'type' => 'Kabupaten', 'postal_code' =>'87112'],
        ['id' => 438, 'province_id' =>  22,'name' =>  'Sumbawa', 'type' => 'Kabupaten', 'postal_code' =>'84315'],
        ['id' => 439, 'province_id' =>  22,'name' =>  'Sumbawa Barat', 'type' => 'Kabupaten', 'postal_code' =>'84419'],
        ['id' => 440, 'province_id' =>  9, 'name' => 'Sumedang', 'type' => 'Kabupaten', 'postal_code' =>'45326'],
        ['id' => 441, 'province_id' =>  11,'name' =>  'Sumenep', 'type' => 'Kabupaten', 'postal_code' =>'69413'],
        ['id' => 442, 'province_id' =>  8, 'name' => 'Sungaipenuh', 'type' => 'Kota', 'postal_code' => '37113'],
        ['id' => 443, 'province_id' =>  24,'name' =>  'Supiori', 'type' => 'Kabupaten', 'postal_code' =>'98164'],
        ['id' => 444, 'province_id' =>  11,'name' =>  'Surabaya', 'type' => 'Kota', 'postal_code' => '60119'],
        ['id' => 445, 'province_id' =>  10,'name' =>  'Surakarta (Solo)', 'type' => 'Kota', 'postal_code' => '57113'],
        ['id' => 446, 'province_id' =>  13,'name' =>  'Tabalong', 'type' => 'Kabupaten', 'postal_code' =>'71513'],
        ['id' => 447, 'province_id' =>  1, 'name' => 'Tabanan', 'type' => 'Kabupaten', 'postal_code' =>'82119'],
        ['id' => 448, 'province_id' =>  28,'name' =>  'Takalar', 'type' => 'Kabupaten', 'postal_code' =>'92212'],
        ['id' => 449, 'province_id' =>  25,'name' =>  'Tambrauw', 'type' => 'Kabupaten', 'postal_code' =>'98475'],
        ['id' => 450, 'province_id' =>  16,'name' =>  'Tana Tidung', 'type' => 'Kabupaten', 'postal_code' =>'77611'],
        ['id' => 451, 'province_id' =>  28,'name' =>  'Tana Toraja', 'type' => 'Kabupaten', 'postal_code' =>'91819'],
        ['id' => 452, 'province_id' =>  13,'name' =>  'Tanah Bumbu', 'type' => 'Kabupaten', 'postal_code' =>'72211'],
        ['id' => 453, 'province_id' =>  32,'name' =>  'Tanah Datar', 'type' => 'Kabupaten', 'postal_code' =>'27211'],
        ['id' => 454, 'province_id' =>  13,'name' =>  'Tanah Laut', 'type' => 'Kabupaten', 'postal_code' =>'70811'],
        ['id' => 455, 'province_id' =>  3, 'name' => 'Tangerang', 'type' => 'Kabupaten', 'postal_code' =>'15914'],
        ['id' => 456, 'province_id' =>  3, 'name' => 'Tangerang', 'type' => 'Kota', 'postal_code' => '15111'],
        ['id' => 457, 'province_id' =>  3, 'name' => 'Tangerang Selatan', 'type' => 'Kota', 'postal_code' => '15332'],
        ['id' => 458, 'province_id' =>  18,'name' =>  'Tanggamus', 'type' => 'Kabupaten', 'postal_code' =>'35619'],
        ['id' => 459, 'province_id' =>  34,'name' =>  'Tanjung Balai', 'type' => 'Kota', 'postal_code' => '21321'],
        ['id' => 460, 'province_id' =>  8, 'name' => 'Tanjung Jabung Barat', 'type' => 'Kabupaten', 'postal_code' =>'36513'],
        ['id' => 461, 'province_id' =>  8, 'name' => 'Tanjung Jabung Timur', 'type' => 'Kabupaten', 'postal_code' =>'36719'],
        ['id' => 462, 'province_id' =>  17,'name' =>  'Tanjung Pinang', 'type' => 'Kota', 'postal_code' => '29111'],
        ['id' => 463, 'province_id' =>  34,'name' =>  'Tapanuli Selatan', 'type' => 'Kabupaten', 'postal_code' =>'22742'],
        ['id' => 464, 'province_id' =>  34,'name' =>  'Tapanuli Tengah', 'type' => 'Kabupaten', 'postal_code' =>'22611'],
        ['id' => 465, 'province_id' =>  34,'name' =>  'Tapanuli Utara', 'type' => 'Kabupaten', 'postal_code' =>'22414'],
        ['id' => 466, 'province_id' =>  13,'name' =>  'Tapin', 'type' => 'Kabupaten', 'postal_code' =>'71119'],
        ['id' => 467, 'province_id' =>  16,'name' =>  'Tarakan', 'type' => 'Kota', 'postal_code' => '77114'],
        ['id' => 468, 'province_id' =>  9, 'name' => 'Tasikmalaya', 'type' => 'Kabupaten', 'postal_code' =>'46411'],
        ['id' => 469, 'province_id' =>  9, 'name' => 'Tasikmalaya', 'type' => 'Kota', 'postal_code' => '46116'],
        ['id' => 470, 'province_id' =>  34,'name' =>  'Tebing Tinggi', 'type' => 'Kota', 'postal_code' => '20632'],
        ['id' => 471, 'province_id' =>  8, 'name' => 'Tebo', 'type' => 'Kabupaten', 'postal_code' =>'37519'],
        ['id' => 472, 'province_id' =>  10,'name' =>  'Tegal', 'type' => 'Kabupaten', 'postal_code' =>'52419'],
        ['id' => 473, 'province_id' =>  10,'name' =>  'Tegal', 'type' => 'Kota', 'postal_code' => '52114'],
        ['id' => 474, 'province_id' =>  25,'name' =>  'Teluk Bintuni', 'type' => 'Kabupaten', 'postal_code' =>'98551'],
        ['id' => 475, 'province_id' =>  25,'name' =>  'Teluk Wondama', 'type' => 'Kabupaten', 'postal_code' =>'98591'],
        ['id' => 476, 'province_id' =>  10,'name' =>  'Temanggung', 'type' => 'Kabupaten', 'postal_code' =>'56212'],
        ['id' => 477, 'province_id' =>  20,'name' =>  'Ternate', 'type' => 'Kota', 'postal_code' => '97714'],
        ['id' => 478, 'province_id' =>  20,'name' =>  'Tidore Kepulauan', 'type' => 'Kota', 'postal_code' => '97815'],
        ['id' => 479, 'province_id' =>  23,'name' =>  'Timor Tengah Selatan', 'type' => 'Kabupaten', 'postal_code' =>'85562'],
        ['id' => 480, 'province_id' =>  23,'name' =>  'Timor Tengah Utara', 'type' => 'Kabupaten', 'postal_code' =>'85612'],
        ['id' => 481, 'province_id' =>  34,'name' =>  'Toba Samosir', 'type' => 'Kabupaten', 'postal_code' =>'22316'],
        ['id' => 482, 'province_id' =>  29,'name' =>  'Tojo Una-Una', 'type' => 'Kabupaten', 'postal_code' =>'94683'],
        ['id' => 483, 'province_id' =>  29,'name' =>  'Toli-Toli', 'type' => 'Kabupaten', 'postal_code' =>'94542'],
        ['id' => 484, 'province_id' =>  24,'name' =>  'Tolikara', 'type' => 'Kabupaten', 'postal_code' =>'99411'],
        ['id' => 485, 'province_id' =>  31,'name' =>  'Tomohon', 'type' => 'Kota', 'postal_code' => '95416'],
        ['id' => 486, 'province_id' =>  28,'name' =>  'Toraja Utara', 'type' => 'Kabupaten', 'postal_code' =>'91831'],
        ['id' => 487, 'province_id' =>  11,'name' =>  'Trenggalek', 'type' => 'Kabupaten', 'postal_code' =>'66312'],
        ['id' => 488, 'province_id' =>  19,'name' =>  'Tual', 'type' => 'Kota', 'postal_code' => '97612'],
        ['id' => 489, 'province_id' =>  11,'name' =>  'Tuban', 'type' => 'Kabupaten', 'postal_code' =>'62319'],
        ['id' => 490, 'province_id' =>  18,'name' =>  'Tulang Bawang', 'type' => 'Kabupaten', 'postal_code' =>'34613'],
        ['id' => 491, 'province_id' =>  18,'name' =>  'Tulang Bawang Barat', 'type' => 'Kabupaten', 'postal_code' =>'34419'],
        ['id' => 492, 'province_id' =>  11,'name' =>  'Tulungagung', 'type' => 'Kabupaten', 'postal_code' =>'66212'],
        ['id' => 493, 'province_id' =>  28,'name' =>  'Wajo', 'type' => 'Kabupaten', 'postal_code' =>'90911'],
        ['id' => 494, 'province_id' =>  30,'name' =>  'Wakatobi', 'type' => 'Kabupaten', 'postal_code' =>'93791'],
        ['id' => 495, 'province_id' =>  24,'name' =>  'Waropen', 'type' => 'Kabupaten', 'postal_code' =>'98269'],
        ['id' => 496, 'province_id' =>  18,'name' =>  'Way Kanan', 'type' => 'Kabupaten', 'postal_code' =>'34711'],
        ['id' => 497, 'province_id' =>  10,'name' =>  'Wonogiri', 'type' => 'Kabupaten', 'postal_code' =>'57619'],
        ['id' => 498, 'province_id' =>  10,'name' =>  'Wonosobo', 'type' => 'Kabupaten', 'postal_code' =>'56311'],
        ['id' => 499, 'province_id' =>  24,'name' =>  'Yahukimo', 'type' => 'Kabupaten', 'postal_code' =>'99041'],
        ['id' => 500, 'province_id' =>  24,'name' =>  'Yalimo', 'type' => 'Kabupaten', 'postal_code' =>'99481'],
        ['id' => 501, 'province_id' =>  5, 'name' => 'Yogyakarta', 'type' => 'Kota', 'postal_code' => '55111']
        ];

        City::insert($data);
    }

}
